environment:
  global:
    CYG_ROOT: C:/cygwin

install:
  - ps: '(new-object net.webclient).DownloadString("http://aantron.github.io/binaries/cygwin/x86/ocaml/4.04/install.ps1") | PowerShell -Command -'
  - ps: '(new-object net.webclient).DownloadString("http://aantron.github.io/binaries/cygwin/x86/camlp4/4.04/install.ps1") | PowerShell -Command -'
  - ps: '(new-object net.webclient).DownloadString("http://aantron.github.io/binaries/cygwin/x86/opam/1.2/install.ps1") | PowerShell -Command -'
  - ps: '(new-object net.webclient).DownloadString("http://aantron.github.io/binaries/cygwin/x86/flexdll/0.35/install.ps1") | PowerShell -Command -'
  - '%CYG_ROOT%\bin\bash -lc "cygcheck -dc cygwin"'
  - '%CYG_ROOT%\bin\bash -lc "echo \"OCaml version `ocamlc -version`\""'

build_script:
  - 'echo Build in "%APPVEYOR_BUILD_FOLDER%"'
  - '%CYG_ROOT%/bin/bash -l "%APPVEYOR_BUILD_FOLDER%/appveyor_build.sh"'
